project_name: 'Real-time Transaction Analytics and Monitoring'
app_name: 'RTAM'
env: 'LOCAL'

graph_db:
  dbms_name : 'Neo4J'
  uri : 'neo4j+s://8ff23937.databases.neo4j.io'
  username : 'neo4j'
  password : 'HYyQNQgQugZfq-L1uujmnhOQDv1Oji6Li3KaLNiAg9E'

main_db:
  dbms_name : 'PostgreSQL'
  uri : 'postgresql://neondb_owner:Ft3vqRmDxA8s@ep-orange-term-a511wxk5.us-east-2.aws.neon.tech/neondb?sslmode=require'

data:
  chunk_size: 10000

notification:
  enabled: true

server:
  http:
    nthreads: 4
    port: 5000